export enum GenericExceptionStatuses {
  ARGUMENT_INVALID = 'GENERIC.ARGUMENT_INVALID',
  AGRUMENT_OUT_OF_RANGE = 'GENERIC.AGRUMENT_OUT_OF_RANGE',
  EXISTING_DATA_CONFLICT = 'GENERIC.EXISTING_DATA_CONFLICT',
  UNEXPECTED_ERROR = 'GENERIC.UNEXPECTED_ERROR',
  ARGUMENT_NOT_PROVIDED = 'GENERIC.ARGUMENT_NOT_PROVIDED'
}
